apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitmagnet-config-pv
  namespace: media
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /volumes/hdd/k3s/bitmagnet
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitmagnet-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: bitmagnet-config-pv