apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /volumes/ssd/k3s/bazarr_config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: bazarr-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-data-pv
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /volumes/hdd/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Ti
  volumeName: bazarr-data-pv
