apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /volumes/hdd/k3s/homarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: homarr-pv