apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /volumes/ssd/k3s/sonarr_config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: sonarr-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-data-pv
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /volumes/hdd/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Ti
  volumeName: sonarr-data-pv
