apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Sao_Paulo"
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: config
              mountPath: /config
            - name: filmes
              mountPath: /movies
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: filmes
          persistentVolumeClaim:
            claimName: radarr-filmes-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: radarr-downloads-pvc