apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TZ
              value: "America/Sao_Paulo"
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources:
            requests:
              cpu: "0.05"
              memory: "100Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config-pvc